### Verbo GET – listar todos
GET http://localhost:8000/produto/ HTTP/1.1

### Verbo GET – listar um
GET http://localhost:8000/produto/1 HTTP/1.1

### Verbo POST – adicionar

POST http://127.0.0.1:8000/produto/ HTTP/1.1
Content-Type: application/json

{
    "nome": "teste",
    "descricao": "teste2",
    "foto": "foto",
    "valor_unitario": 12
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/produto/1 HTTP/1.1
Content-Type: application/json

{
    "nome": "FelipeMaines Editado",
    "descricao": "string",
    "foto": "fotoads",
    "valor_unitario": 0
}

### verbo Delete
DELETE http://127.0.0.1:8000/produto/1 HTTP/1.1


